version: '3'
services:
  web:
    build: ./web
    volumes:
      - ./web:/code
      - /code/node_modules
    command: npm run dev
    ports:
      - "8080:8080"
    depends_on:
      - api
      - db
  api:
    build: ./api
    volumes:
      - ./api:/code
    command: python ./server.py
    ports:
      - "5002:5002"
    depends_on:
      - db
  db:
    image: postgres:latest
    ports:
      - "9999:5432"
    volumes:
      - ./db:/db
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: db
      POSTGRES_PASSWORD: db
